add virtual-kubelet provider for armada to LFX ideas
cncf/mentoring pull request #1034
Opened 2023-07-20 20:49 UTC by kannon92

Project idea for Armada for Fall LFX Mentorship

2023-07-20 22:09 UTC, nate-double-u requested changes
Thanks for this @kannon92!

It looks like part of the description is missing. Would you mind updating it?

2023-07-24 06:44 UTC, RohanSasne commented on programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
> +- Description: (Virtual Kubelet)[https://github.com/virtual-kubelet/virtual-kubelet] is a way to bring a Kubernetes front end and allow for your execution environment to be something other than Kuber
```suggestion
- Description: [Virtual Kubelet](https://github.com/virtual-kubelet/virtual-kubelet) is a way to bring a Kubernetes front end and allow for your execution environment to be something other than Kubernetes. We want to add a virtual-kubelet provider so we can allow for
```

2023-07-24 06:44 UTC, RohanSasne commented on programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
> +- Description: (Virtual Kubelet)[https://github.com/virtual-kubelet/virtual-kubelet] is a way to bring a Kubernetes front end and allow for your execution environment to be something other than Kuber
Little quick fix over here 😁

2023-07-24 16:44 UTC, nate-double-u approved these changes
Thanks a lot for this @kannon92!

2023-07-24 16:44 UTC, merged