Add Volcano Project Ideas for Fall LFX2023
cncf/mentoring pull request #1062
Opened 2023-08-01 14:06 UTC by william-wang

2023-08-01 18:27 UTC, nate-double-u requested changes
Thanks for this @william-wang & team (@wangyang0616, @Thor-wl).

2023-08-01 18:27 UTC, nate-double-u commented on programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
> -```
Please don't delete the template  🙂

2023-08-02 13:51 UTC, nate-double-u commented
Friendly nudge @william-wang 🙂

2023-08-03 11:56 UTC, Thor-wl commented
> Friendly nudge @william-wang 🙂

@nate-double-u William may be very busy recently. May I submit another PR for that?

2023-08-03 12:20 UTC, closed without merging

2023-08-03 12:48 UTC, william-wang commented
> Friendly nudge @william-wang 🙂

Thanks for your reminding. I resubmit another pr :)