Add arewefastyet vitess LFX project for fall 2023
cncf/mentoring pull request #1065
Opened 2023-08-02 13:23 UTC by frouioui

Hello @nate-double-u, this PR adds the proposal for the Vitess' LFX project during the next term.

2023-08-02 13:50 UTC, nate-double-u requested changes
Hi @frouioui, I'm a little confused—this already looks to be set up. Are you proposing a second term of this?

Could you add Vitess to the Table of Contents?

2023-08-02 13:52 UTC, frouioui commented
> Hi @frouioui, I'm a little confused—this already looks to be set up. Are you proposing a second term of this?
> 
> Could you add Vitess to the Table of Contents?

Hey @nate-double-u. I am proposing a second term to continue what the current intern has started. Should I open a second issue on the `vitessio/arewefastyet` repository or keep the same as the first term?

I'll change the table of content and remove the URL.

2023-08-02 13:53 UTC, frouioui commented on programs/lfx-mentorship/2023/03-Sep-Nov/README.md
> +- LFX URL: https://mentorship.lfx.linuxfoundation.org/project/8299d27a-9e36-4de6-abbc-c9282634ee03
Fixed via c62e776.

2023-08-02 23:10 UTC, frouioui commented
> Would there be a new mentee? Unfortunately mentees can only participate in one LFX Mentorship term.

@nate-double-u yes, there would be a new mentee.

2023-08-02 23:14 UTC, tanayvaswani commented
@nate-double-u I think @frouioui has some plans with the project that was also a part of previous term, and he wants somebody new as a mentee this time, to be working ahead with him, am I right @frouioui? 
Also, from an applicant's point of view it would be great if you can create a new issue and mention all the progress which has been done by the previous mentee @frouioui. 
Thanks :)

2023-08-02 23:15 UTC, frouioui commented
> I think @frouioui has some plans with the project that was also a part of previous term, and he wants somebody new as a mentee this time, to be working ahead with him, am I right @frouioui?

That's totally correct @tanayvaswani, thank you!

> Also, from an applicant's point of view it would be great if you can create a new issue and mention all the progress which has been done by the previous mentee @frouioui.

Good idea, I will do that!

2023-08-03 14:17 UTC, frouioui commented
[A new issue](https://github.com/vitessio/arewefastyet/issues/415) has been linked.

2023-08-03 17:03 UTC, nate-double-u commented
Thanks for the updates!

Adding the hold label as this needs to be enrolled in the LFX platform and approved by them.
I'll add the LFX URL link once I get it, and will add it as a suggested change.

2023-08-03 17:16 UTC, nate-double-u approved these changes
Please do not merge PR till we get LFX approvals.

2023-08-03 17:16 UTC, nate-double-u commented on programs/lfx-mentorship/2023/03-Sep-Nov/README.md
> +  - @fouioui Florent Poinsard frouioui@planetscale.com
```suggestion
  - Florent Poinsard @fouioui frouioui@planetscale.com
```

2023-08-03 17:16 UTC, nate-double-u commented on programs/lfx-mentorship/2023/03-Sep-Nov/README.md
> +- LFX URL:
```suggestion
- LFX URL: https://mentorship.lfx.linuxfoundation.org/project/10d70edd-60ec-409b-8801-0fb752501b12
```

2023-08-04 04:12 UTC, nate-double-u commented
LFX approved, removing hold.

2023-08-04 04:13 UTC, merged

2023-08-04 14:41 UTC, frouioui commented
Thank you @nate-double-u!