Adding CNCF LFX 2024 Term 3 Sept-Nov
cncf/mentoring pull request #1220
Opened 2024-05-01 23:10 UTC by nate-double-u

Setting up CNCF LFX 2024 Term 3 Sept-Nov

resolves #1107

2024-05-02 10:31 UTC, aliok requested changes

2024-05-02 10:31 UTC, aliok commented on programs/lfx-mentorship/2024/03-Sep-Nov/README.md
> +# Term 02 - 2024 June - August
```suggestion
# Term 02 - 2024 September - November
```

2024-05-02 10:31 UTC, aliok commented on programs/lfx-mentorship/2024/03-Sep-Nov/README.md
> +Project maintainers and potential mentors are welcome to propose their mentoring project ideas via submitting a PR to GitHub here https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2
```suggestion
Project maintainers and potential mentors are welcome to propose their mentoring project ideas via submitting a PR to GitHub here [2024/03-Sep-Nov/project_ideas.md](./project_ideas.md), by July 23, 2024.
```

2024-05-08 19:49 UTC, nate-double-u commented
If it looks good, let's merge it in 🙂

2024-05-08 19:50 UTC, aliok approved these changes

2024-05-08 19:50 UTC, merged