LFX Summer 2024: Service Mesh Performance
cncf/mentoring pull request #1246
Opened 2024-05-10 22:55 UTC by Yashsharma1911

2024-05-13 19:42 UTC, nate-double-u commented
Hi @Yashsharma1911, thanks for this!

@leecalcote & @gyohuangxin could you 👍 or approve this PR to confirm your participation?

2024-05-13 19:43 UTC, nate-double-u commented
Also, @Yashsharma1911, could you resolve the merge conflicts?

2024-05-14 08:26 UTC, Yashsharma1911 commented on programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
> +
```suggestion
```

2024-05-14 08:26 UTC, Yashsharma1911 commented on programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
> +
Unnecessary space change

2024-05-14 08:26 UTC, Yashsharma1911 commented
> Also, @Yashsharma1911, could you resolve the merge conflicts?

Thankyou @nate-double-u merge conflicts are now resolved

2024-05-14 08:35 UTC, Yashsharma1911 commented on programs/lfx-mentorship/2024/02-Jun-Aug/README.md
> +  - [Service Mesh Performance: Convergence of Network and Graph topologies](service-mesh-performance-convergence-of-network-and-graph-topologies)
```suggestion
- [Service Mesh Performance](#service-mesh-performance)
  - [Service Mesh Performance: Convergence of Network and Graph topologies](#service-mesh-performance-convergence-of-network-and-graph-topologies)
```

2024-05-14 18:47 UTC, leecalcote approved these changes
LGTM

2024-05-14 21:26 UTC, nate-double-u commented
Thanks for the update, we're still waiting on a 👍 or approval from @gyohuangxin

2024-05-14 21:38 UTC, nate-double-u requested changes
This should target `programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md`, part of our process is moving from project ideas to the README as the LFX approves the project.

2024-05-14 23:06 UTC, nate-double-u approved these changes
Thanks for the updates @Yashsharma1911

/approve
/hold

(hold while we wait for confirmation from @gyohuangxin)

2024-05-15 01:16 UTC, gyohuangxin approved these changes
LGTM, thanks!

2024-05-15 17:08 UTC, merged