Proposal of Kubespray project for LFX 2024 Jun-Aug
cncf/mentoring pull request #1247
Opened 2024-05-14 06:58 UTC by yankay

ref https://github.com/kubernetes-sigs/kubespray/issues/5432

2024-05-14 07:38 UTC, MadhavJivrajani commented
Explicit +1 from me 

with my SIG ContribEx hat on.

2024-05-14 12:25 UTC, palnabarun commented
Explicit +1 with the steering hat on

2024-05-14 17:02 UTC, nate-double-u reviewed
thanks for this @yankay!

I have a couple comments in line :)

2024-05-15 05:12 UTC, yankay commented on programs/lfx-mentorship/2024/02-Jun-Aug/README.md
> +- Description: Kubespray is a sig project of kubernetes. It helps deploy a production-ready Kubernetes cluster with ansible. The project Kubespray wants maintainers to help fix the bug and enhance th
Thanks @nate-double-u 
It has been changed :-)

2024-05-15 07:30 UTC, yankay commented on programs/lfx-mentorship/2024/02-Jun-Aug/README.md
> +    - Kay Yan (yankay, <kay.yan@daocloud.io>)
HI @nate-double-u 

@mzaian will join as another mentor :-)

2024-05-15 17:09 UTC, nate-double-u commented on programs/lfx-mentorship/2024/02-Jun-Aug/README.md
> +    - Kay Yan (yankay, <kay.yan@daocloud.io>)
Awesome, thanks @yankay & @mzaian!

2024-05-15 17:09 UTC, nate-double-u approved these changes

2024-05-15 17:10 UTC, nate-double-u requested changes
This should target programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md, part of our process is moving from project ideas to the README as the LFX approves the project.

I can make this change myself, but I wanted to let you know I'll be moving it shortly.

2024-05-15 17:26 UTC, nate-double-u commented
Oh wait, this has already been setup on LFX earlier. I think we may be best to create a new one to keep things in line with the way we run the other projects. CNCF Mentorshipadmins will own the project, and I'll invite @yankay and @mzaian as mentors.

2024-05-15 17:32 UTC, nate-double-u approved these changes

2024-05-15 17:32 UTC, merged

2024-05-16 02:14 UTC, yankay commented
@nate-double-u 
Thank you 🎉🎉🎉