lfx-spring-2022: k8s: add project for maintainers automation
cncf/mentoring pull request #459
Opened 2022-02-01 05:48 UTC by nikhita

Already discussed with @dims. We'll add a link to an issue with the complete task last once the maintainers repo is migrated over.

cc @palnabarun @mrbobbytables @idvoretskyi

2022-02-01 07:00 UTC, idvoretskyi approved these changes

2022-02-01 07:02 UTC, idvoretskyi requested changes

2022-02-01 07:02 UTC, idvoretskyi commented on lfx-mentorship/2022/01-Spring/project_ideas.md
> +##### Docuemntation assessment (SIG-Network Gateway API)
Typo :)

2022-02-01 20:29 UTC, idvoretskyi commented on lfx-mentorship/2022/01-Spring/project_ideas.md
> +##### Docuemntation assessment (SIG-Network Gateway API)
Fixed.

2022-02-01 20:29 UTC, idvoretskyi approved these changes

2022-02-01 20:29 UTC, merged

2022-02-02 03:06 UTC, nikhita commented
@idvoretskyi sorry for the delay, and thanks for fixing the typo! :smile: