details for Kyverno projects
cncf/mentoring pull request #531
Opened 2022-02-28 21:32 UTC by JimBugwadia

Signed-off-by: Jim Bugwadia <jim@nirmata.com>

2022-02-28 22:54 UTC, nate-double-u requested changes
Thanks for the updates @JimBugwadia, could you please revise and use 175 or 350 hours.

2022-02-28 22:54 UTC, nate-double-u commented on summerofcode/2022.md
> +- Expected project size: 200 hours
Please use 175 or 350 hours.

2022-02-28 22:54 UTC, nate-double-u commented on summerofcode/2022.md
> +- Expected project size: 250 hours
Please use 175 or 350 hours.

2022-02-28 22:54 UTC, nate-double-u commented on summerofcode/2022.md
> +- Expected project size: 240 hours
Please use 175 or 350 hours.

2022-03-01 06:16 UTC, JimBugwadia commented
Hi @nate-double-u - done! Thanks!

2022-03-01 16:24 UTC, nate-double-u approved these changes
Thanks for the updates @JimBugwadia

2022-03-01 16:26 UTC, merged