Feat: add kubevela sdk auto-generation proposal
cncf/mentoring pull request #772
Opened 2023-01-24 16:11 UTC by chivalryq

Add KubeVela SDK auto-generation proposal for LFX 2023.

Ref: https://github.com/kubevela/kubevela/issues/5365

2023-01-24 17:59 UTC, nate-double-u requested changes
Hi @chivalryq, thanks for this proposal!

We do need a maintainer to participate in mentorship projects -- are you able to add someone from the KubeVela maintainers group to work with you as a mentor as well?

@wonderflow is this a project you'd be able to participate in along with [the other](https://github.com/cncf/mentoring/pull/764) [ones](https://github.com/cncf/mentoring/pull/767)?

2023-01-26 00:49 UTC, wonderflow commented
Ping @barnettZQG

2023-01-26 02:25 UTC, barnettZQG commented
@nate-double-u I am happy to as a mentor for this proposal.

2023-01-26 03:17 UTC, chivalryq commented
@nate-double-u Added @barnettZQG.

2023-01-26 16:14 UTC, merged