WIP: Add project ideas for Harbor
cncf/mentoring pull request #798
Opened 2023-01-31 14:01 UTC by OrlinVasilev

Signed-off-by: OrlinVasilev <ovasilev@vmware.com>

2023-01-31 14:01 UTC, OrlinVasilev commented
@vad1mo please check here

2023-01-31 22:23 UTC, OrlinVasilev commented
@nate-double-u ready for review :) thank you!

2023-01-31 23:01 UTC, Vad1mo approved these changes

2023-02-01 03:30 UTC, nate-double-u requested changes
Thanks for this @OrlinVasilev!

Could you please add Mentor names and email addresses to the mentors lists in addition to their github handles?

2023-02-01 03:33 UTC, nate-double-u commented
(if you don't want to share their email addresses here, please reach out to me in slack)

2023-02-01 06:27 UTC, OrlinVasilev commented on lfx-mentorship/2023/01-Mar-May/project_ideas.md
> +- Recommended Skills: Golang
done

2023-02-01 06:27 UTC, OrlinVasilev commented
@nate-double-u done :)

2023-02-01 17:18 UTC, nate-double-u approved these changes
Thanks for the updates @OrlinVasilev!

2023-02-01 17:18 UTC, merged